import 'react-native'
import React from 'react'
import ReactShallowRenderer from 'react-test-renderer/shallow'
import RootNavigator from './index'

jest.mock('react-native-google-signin')
jest.mock('react-native-zss-rich-text-editor')

// NOTE: filterKeys and prepareForSnapshot are simple for removing the time
// generated keys on the react-test output of a react-navigation navigator
// or router. They are extraneous data to the snapshots in these cases.
//
// * The keys generated by react-navigation are Date.now() based but the
// Date.now() capture is at the level of the module definition not within
// a function making it difficult to mock (see line 25 in node_modules/
// react-navigation/src/routers/StackRouter.js)
//
// These functions could be moved to a test util/helper file  or otherwise
// we can figure-out how to properly mock/unmock Date.now() such that it applies
// to this react-navigation component definition.
//
// See: https://github.com/react-community/react-navigation/issues/2269
//
function filterKeys (state) {
  if (state.routes) {
    return {
      ...state,
      routes: state.routes.map(route => {
        const { key, ...others } = route
        return filterKeys(others)
      })
    }
  }
  return state
}

function prepareForSnapshot (output) {
  output.props.navigation.state = filterKeys(output.props.navigation.state)
  return output
}

it('matches snapshot', () => {
  const renderer = new ReactShallowRenderer()
  renderer.render(<RootNavigator uriPrefix={'lala'} />)
  const output = prepareForSnapshot(renderer.getRenderOutput())
  expect(output).toMatchSnapshot()
})
