const errorFunc = global.console.error

global.console.error = (err) => {
  // Suppress warnings generated by other packages we don't control
  if (err.includes('PropTypes has been moved')) return
  if (err.includes('React.createClass is no longer supported')) return
  if (err.includes('View.propTypes has been deprecated')) return
  errorFunc(err)
}
