// console.log('************************')
// console.log('************************')
// console.log('************************')
// console.log('************************')
// console.log('************************')
// console.log('************************')
// console.log(' ')
// console.log('set up mock')
// console.log(' ')
// console.log('************************')
// console.log('************************')
// console.log('************************')
// console.log('************************')
// console.log('************************')
// console.log('************************')

require('react-native-mock/mock')
