engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**
exclude_paths:
- "**/index.js"
- "**/*.test.js"
- "**/*.styles.js"
