/**
 * @providesModule store/constants
 */

export const EXTRACT_MODEL = 'EXTRACT_MODEL'
export const JOIN_PROJECT = 'JOIN_PROJECT'
export const JOIN_PROJECT_PENDING = 'JOIN_PROJECT_PENDING'
export const LEAVE_PROJECT = 'LEAVE_PROJECT'
export const LEAVE_PROJECT_PENDING = 'LEAVE_PROJECT_PENDING'
export const LOG_ERROR = 'LOG_ERROR'
export const SELECT_COMMUNITY = 'SELECT_COMMUNITY'
export const SELECT_NETWORK = 'SELECT_NETWORK'
export const SET_STATE = 'SET_STATE'
export const TRACK_ANALYTICS_EVENT = 'TRACK_ANALYTICS_EVENT'
