/**
 * @providesModule store/constants
 */

export const BLOCK_USER = 'BLOCK_USER'
export const EXTRACT_MODEL = 'EXTRACT_MODEL'
export const FETCH_PEOPLE_AUTOCOMPLETE = 'FETCH_PEOPLE_AUTOCOMPLETE'
export const FETCH_RECENT_CONTACTS = 'FETCH_RECENT_CONTACTS'
export const FETCH_TOPICS_FOR_COMMUNITY_ID = 'FETCH_TOPICS_FOR_COMMUNITY_ID'
export const JOIN_PROJECT = 'JOIN_PROJECT'
export const JOIN_PROJECT_PENDING = 'JOIN_PROJECT_PENDING'
export const LEAVE_PROJECT = 'LEAVE_PROJECT'
export const LEAVE_PROJECT_PENDING = 'LEAVE_PROJECT_PENDING'
export const LOG_ERROR = 'LOG_ERROR'
export const RESET_STORE = 'RESET_STORE'
export const SELECT_COMMUNITY = 'SELECT_COMMUNITY'
export const SELECT_NETWORK = 'SELECT_NETWORK'
export const SET_QUERY_SEARCH_TERM = 'SET_QUERY_SEARCH_TERM'
export const SET_STATE = 'SET_STATE'
export const TRACK_ANALYTICS_EVENT = 'TRACK_ANALYTICS_EVENT'
export const UNBLOCK_USER = 'UNBLOCK_USER'
