# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HyloReactNative' do
  use_frameworks!

  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
end
