platform :ios, '9.0'

target 'HyloReactNative' do
  use_frameworks!

  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end
